apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Taskcluster
  region: ap-south-1

nodeGroups:
   - name: ng1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: mycloudkey1
   - name: ng2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: mycloudkey1
